#!/bin/bash

#┌──────────────────────────────────┐
#│ Устанавливаем базовые npm-пакеты │
#└──────────────────────────────────┘
if [ ! -e "./node_modules" ]; then
    clear
    npm cache clean --force
    npm install --no-package-lock
fi

#┌───────────────────────────────┐
#│ Устанавливаем sails глобально │
#└───────────────────────────────┘
if ! sails -v >/dev/null 2>&1; then
    clear
    npm install --no-package-lock --global sails
fi

#┌──────────────────────┐
#│ Запускаем приложение │
#└──────────────────────┘
clear
sails lift
